services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: sqlite
      DB_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - aihan-database:/var/www/html/database

volumes:
  aihan-database:
